name: deploy

on: 
  pull_request:
    branches:
      - v1
jobs:
  generate-release-notes-body:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: matsuri-tech/generate-release-notes-body-based-on-pull-requests@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_PREFIX: 'Release Note'
