name: "units-test"
on:
  pull_request:

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_PREFIX: 'Release Note'
